export const colors = {
  background: "#fcf9f8",
  surface: "#fcf9f8",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f6f3f2",
  surfaceContainer: "#f0eded",
  surfaceContainerHigh: "#eae7e7",
  surfaceVariant: "#e5e2e1",
  onSurface: "#1c1b1b",
  onSurfaceVariant: "#554244",
  outline: "#887173",
  outlineVariant: "#dbc0c2",
  primary: "#56001b",
  primaryContainer: "#741a2f",
  onPrimary: "#ffffff",
  primaryFixed: "#ffd9dc",
  primaryFixedDim: "#ffb2bb",
  secondary: "#7f543d",
  secondaryContainer: "#fec5a7",
  onSecondaryContainer: "#7a5038",
  tertiary: "#002e1c",
  tertiaryContainer: "#00472d",
  error: "#ba1a1a",
  white: "#ffffff"
};
